
apiVersion: getambassador.io/v1
kind:  Module
metadata:
  name:  ambassador
spec:
  config:
    enable_grpc_web: true
    cors:
      origins: "http://localhost:3000"
      methods: GET, PUT, DELETE, POST, OPTIONS
      headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
      max_age: "1728000"
      exposed_headers: custom-header-1,grpc-status,grpc-message
      credentials: true
